### ISSUE TITLE
attach to elixir node

### ISSUE THREAD

**Issue by oltarasenko** [tsloughter/epmdless#25]
Hey @tsloughter,

I think the node attach is not working currently for the elixir case, on Otp23.
E.g. I was trying to do the:
```
/app # ERL_DIST_PORT=18011 bin/myapp remote
Erlang/OTP 23 [erts-11.0.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]

Could not contact remote node app@node1.com, reason: :nodedown. Aborting..
```

Could you please advise what can be done in the case?

**Comment by tsloughter** [comment]
@oltarasenko any more info on this? I just released there wasn't a release of epmdless despite plenty of changes. Were you using the hex package?

**Comment by oltarasenko** [comment]
@tsloughter no I don't need any additional information now. Thanks!
